AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/blank-java.zip
      Handler: authentication.AuthenticationRequestHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Environment:
        Variables:
          COGNITO_DOMAIN_PREFIX: sunnyoauth
          COGNITO_APP_ID: 1vvp0tt53g1uhntoa5bmvnvk2a
          COGNITO_APP_SECRET: <secret>
          API_GATEWAY_URL: https://a7blo97bal.execute-api.us-east-1.amazonaws.com/prod
          # CORS_ALLOW_ORIGIN: http://localhost:4200
          CORS_ALLOW_ORIGIN: http://athenatestsunny2020.s3-website-us-east-1.amazonaws.com
          # LOGIN_REDIRECT_URL: http://localhost:4200
          LOGIN_REDIRECT_URL: http://athenatestsunny2020.s3-website-us-east-1.amazonaws.com
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-java-lib
      Description: Dependencies for the blank-java sample app.
      ContentUri: build/blank-java-lib.zip
      CompatibleRuntimes:
        - java8