AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
Resources:
  OAuthDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/aws-lambda-authentication-java.zip
      Handler: authentication.AuthenticationRequestHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Environment:
        Variables:
          COGNITO_DOMAIN_PREFIX: sunnyoauth
          COGNITO_APP_ID: 1vvp0tt53g1uhntoa5bmvnvk2a
          COGNITO_APP_SECRET: <secret>
          CORS_ALLOW_ORIGIN: http://localhost:4200
          #CORS_ALLOW_ORIGIN: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com
          LOGIN_REDIRECT_URL: http://localhost:4200
          #LOGIN_REDIRECT_URL: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com
      Layers:
        - !Ref libs
      Events:
        DemoAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-lambda-authentication-java-lib
      Description: Dependencies for the aws-lambda-authentication-java sample app.
      ContentUri: build/aws-lambda-authentication-java-lib.zip
      CompatibleRuntimes:
        - java8
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OAuthDemoApi:
    Description: "API Gateway endpoint URL for Prod stage for OAuth Demo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  OAuthDemoFunction:
    Description: "OAuth Demo Lambda Function ARN"
    Value: !GetAtt OAuthDemoFunction.Arn
  OAuthDemoFunctionIamRole:
    Description: "Implicit IAM Role created for OAuth Demo function"
    Value: !GetAtt OAuthDemoFunctionRole.Arn