package authentication;

public class Constants {
    public final String ENVIRONMENT_VARIABLE_HEALTH_PATH = "ENVIRONMENT_VARIABLE_HEALTH_PATH";
    public final String ENVIRONMENT_VARIABLE_COGNITO_PREFIX = "ENVIRONMENT_VARIABLE_COGNITO_PREFIX";
    public final String ENVIRONMENT_VARIABLE_APP_ID = "ENVIRONMENT_VARIABLE_APP_ID";
    public final String ENVIRONMENT_VARIABLE_APP_SECRET = "ENVIRONMENT_VARIABLE_APP_SECRET";
    public final String ENVIRONMENT_VARIABLE_GATEWAY_URL = "ENVIRONMENT_VARIABLE_GATEWAY_URL";
}
